[build]
  command = "npm run build"
  publish = "build"
  NODE_OPTIONS="--max-old-space-size=4096"

# Default site wide settings
[build.processing]
  skip_processing = true

# Branch specific settings
[context.branch-name.processing]
  skip_processing = false
[context.branch-name.processing.css]
  bundle = true
  minify = true
